### ISSUE TITLE
Image is redownloaded

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#13]
It should be possible to grab the image from the originally loaded page, rather than reloading it. Yet every time I open QC, The image loads, disappears, and then loads again. 

If, for some reason you do have to reload the image, you could delay deleting/hiding the original until the image is completely loaded in the background, and only then replace it--similar to what I suggested in #12

I do know how to tweak JavaScript, so ordinarily I'd try fixing things myself, but I do not understand your framework.

**Comment by ilyvion** [comment]
Strictly speaking, what happens is that the original QC website is fully loaded, then I replace various components on there (such as the image container) with my components (i.e. I do a bunch of DOM manipulations to set up for using AngularJS), and then my code runs and effectively rebuilds the page as a so-called single-page-application.

It's that short period of time when the page consists of the unbuilt AngularJS directives that causes the apparent reloading of the image.

It has been bothering me that it happens, and it's certainly solvable, but it's not high on my priority list because it's mostly just annoying, and not really "broken" as such. Thanks for your report, though, I do intend to fix it eventually.

**Comment by ilyvion** [comment]
The thing is, it's a lot easier to replace whole chunks with your own markup than it is to try to do lots of minute modifications to the existing markup. In retrospect, it was perhaps not worth skipping out on that extra work, considering the consequences.

**Comment by trlkly** [comment]
If you do want to replace it, perhaps you could do it hidden (via CSS, for example), and then replace them all at once, so that the unfinished parts are never actually shown?

I know how much fun it can be to refactor code. This could at least work as a temporary measure.
