### ISSUE TITLE
Add loading indicators where they're missing

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#14]
I am currently running on a slower connection than usual. And I've noticed there is no indication that the subsequent image is loading after clicking on a navigation link. The page just remains the same until the next image fully loads. This can create the illusion that the page/script is broken.

There are two possible fixes: an animation on the link clicked to get to the next image. You could also do some fading on the current image, and fade in the new image. 

Or, just display the new image as it is loading (perhaps after a brief delay--250ms is generally good), which would allow reading part of the comic as it loads. (No delay, of course, if the image finished loading before 250ms.)

I prefer option 2, as you can probably tell.

Note: I noticed this before the upgrade, so it is not caused by #13.

**Comment by ilyvion** [comment]
I'd like to do option 2, but I don't know how to get browsers to do that. The only thing I do when a user navigates to a new comic is change the `src` attribute of the `<img>`. This doesn't cause the image to load like it would on a first load, unfortunately, but rather it causes the browser to download it in the background and replace the existing one once it's done.

Since that's not an option (unless you or somebody else knows a trick to get different behavior), the other option is to have a loading indicator. A very old version of my script (way before I released my script to the public) used to do this. I'll see about doing that.

**Comment by trlkly** [comment]
Quick testing seems to indicate that you can accomplish option 2 by first
setting the img.src to "", and only after that changing it to the desired
URL.

Though that wouldn't have the delay I mentioned.

**Comment by ilyvion** [comment]
Missing locations are:

- ~~Comic image~~ (done)
- ~~When loading item details~~ (already implemented)
- ~~When loading edit log~~ (done)
- ~~Any time any editor action is done~~ (done)

**Comment by trlkly** [comment]
Since the bug was originally submitted by me, I thought I'd voice ideas on what I would expect.

If you can get the loading status of an image that has had its src changed, great. Use that to display some sort of overlay as it loads. But, if not, maybe load the image as a just a new Image(), use its loading status for the overlay, and then replace the original image in the DOM upon load. 

I'd also recommend using a timer on display, and not display the loading image for a certain number of milliseconds when loading. That way, if the image is loaded quickly (e.g. it's already in the browser cache), nothing is covered.

The most obvious and simple overlay would be a spinning circle for all cases (images or others). However, for the image, you might also include some semi-transparent white or black to create a "faded out" effect.

**Comment by ilyvion** [comment]
> Since the bug was originally submitted by me, I thought I'd voice ideas on what I would expect.

That's fair. As project owner and (as of now, only) developer, I could just do whatever I want, but since this is an open source, community-focused project, I should listen to my users; especially the one who brought the idea forth. 😄 

I agree with all your points. Some cursory research suggests that I'm probably going to have to go with the `new Image()` route, if I want loading/progress information.

**Comment by ilyvion** [comment]
I had to do some serious refactoring to prevent the problem from #13 from coming back. 😬 On the other hand, I'm much happier with how the comic loading works now. The other three loading indicators should be much quicker to implement.

I guess we'll see if you like how it turned out when I do my next release!
