### ISSUE TITLE
For updated comics, the possibility of changing which version you're seeing?

### ISSUE THREAD

**Issue by Nixill** [Questionable-Content-Extensions/client#17]
[Strip 2513](http://questionablecontent.net/view.php?comic=2513) has been updated since it was posted, but QE still displays the original version. Perhaps display the updated by default, with a thing in the sidebar saying it was updated?

**Comment by ilyvion** [comment]
> I honestly had never noticed that. For now I suppose you could assume it's jpg first? Or are there other comics where the correct version is png but a jpg version also exists?

I don't want to change the order of assumed file endings, because that'll cause the script to start hammering Jeph's server with requests for jpg comics that for the most part don't exist. I chose the order I did because it would cause the least deviating behavior from the norm.

I think the right way to go about this is to add a field to the database that can explicitly say "this comic uses something else than png, and that is X", where X is gif or jpg or whatever else he might decide to do someday.
