### ISSUE TITLE
Not working on Firefox 57 / Greasemonkey 4

### ISSUE THREAD

**Issue by Nixill** [Questionable-Content-Extensions/client#21]
It simply doesn't load. The error in the console is as follows:

```
Script error:  
ReferenceError
columnNumber: 11763
fileName: "resource://gre/modules/ExtensionContent.jsm"
lineNumber: 405
message: "GM_getValue is not defined"
stack: "userScript/<@user-script:https%3A//questionablextensions.net//Questionable%20Content%20Single-Page%20Application%20with%20Extra%20Features:405:11763\nuserScript@user-script:https%3A//questionablextensions.net//Questionable%20Content%20Single-Page%20Application%20with%20Extra%20Features:405:11487\nscopeWrapper@user-script:https%3A//questionablextensions.net//Questionable%20Content%20Single-Page%20Application%20with%20Extra%20Features:40693:9\n@user-script:https%3A//questionablextensions.net//Questionable%20Content%20Single-Page%20Application%20with%20Extra%20Features:361:17\n"
__proto__: Object { stack: "", … }
```

**Comment by ilyvion** [comment]
Firefox 57 forced Greasemonkey to be rewritten, and the Greasemonkey developers decided to use the opportunity to change their API in such a way as to break backwards compatibility. To quote the developers:

> As a result, version 4 of Greasemonkey is a nearly complete re-write. Its interface and feature set have been rebuilt in order to best to work with coming Firefox versions. A variety of compromises have been made. We've **elected** to make a rare **backwards incompatible change**.

[Source](http://www.greasespot.net/2017/09/greasemonkey-4-announcement.html) (emphasis mine)

I'll eventually get around to it, but I don't have much time to dedicate to this script these days. I'll keep this is mind, though, for sure.

**Comment by ilyvion** [comment]
Oh, by the way, the developers of Greasemonkey even recommend you switch to a different userscript engine than theirs if you want/need old-style scripts to continue working:

> If you rely on such scripts, you might want to install [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) or [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/), both of which provide better compatibility for existing scripts.

[Source](http://www.greasespot.net/2017/09/greasemonkey-4-for-users.html)

**Comment by trlkly** [comment]
I actually have a workaround that gives you GreaseMonkey 4.0 support. Would you be interested? It's currently applied directly to the minified release version, but I am looking into how to apply it to the source. 

My strategy: rather than switch to the new promise-based API, which would take a lot of refactoring, I used the [old grant-none polyfill](https://gist.github.com/arantius/3123124), which implements most of the `GM_` functions in user code. Unfortunately, the polyfilled GM_xmlHttpRequest is domain restricted, and thus doesn't work.  To work around this, I also grant `GM.xmlHttpRequest`  and then, if it exists, map it to GM_xmlhttpRequest. Fortunately this is easy, as they are functionally identical. 

With this I got it working again in a few minutes. If I used Firefox Quantum for more than testing, I might have noticed this and helped out sooner.

**Comment by ilyvion** [comment]
I upgraded my build system and script module system, and replaced the old GM_* functions with the new GM.* functions, so this should be (properly) fixed in the next release. I tested on Firefox and it's all good.
