### ISSUE TITLE
Comic data not being read again / Server can't be reached

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#26]
Seems like #24 or something similar may be flaring up again. The last couple of comics have "null" for the news update and no character or location info on the side.

**Comment by ilyvion** [comment]
I don't know why the news aren't being properly downloaded (and I have neither the time nor the energy to look into it properly right now), but as for lacking character and location data -- my trusty editor who's been keeping the comic data up to date for years now has gone AWOL, and while I try to update it every now and then when I have the time and energy, I'm not as prompt as he was, so it may not be up to date as early as it used to be unless he comes back or I get another trusty editor to help me.

**Comment by trlkly** [comment]
@alexschrod  It actually seems the entire server is down right now. I'm getting "error communicating with server" now.

**Comment by ilyvion** [comment]
Sorry about that. My host is being a nuisance again.

I am (slowly, due to personal reasons/issues) planning to move the hosting of the comic data to a different host, which should hopefully mitigate the various issues I'm having these days, but for now, we're sadly pretty stuck with what we've got.

At least nobody is paying me for this work I've done and am still doing, so I don't feel too bad when it occasionally breaks.

**Comment by ilyvion** [comment]
I believe this has been fixed now. Feel free to re-open the issue if it starts up again.
