### ISSUE TITLE
Changing the "skip" settings has a delay of one navigation before taking effect.

### ISSUE THREAD

**Issue by Nixill** [Questionable-Content-Extensions/client#34]
For example, if you get to 1960 with the skip settings on, turn off skipping non-canon comics, and then hit next (either right arrow or the "next" link), you still go to 1962.

**Comment by ilyvion** [comment]
That makes sense, since it's the server that tells the client which comic comes next, and when you change the setting, the client would need to ask the server if something has changed.

That being said, it should just auto-refresh for you, like when you turn on or off "Show All Members." I dunno why I didn't have it do that already.

**Comment by ilyvion** [comment]
This was fixed while working on 1.0.
