### ISSUE TITLE
Sidebar missing on direct links to comic pages

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#37]
It seems that the sidebar no longer wants to embed whenever you load a comic page directly.

It still works fine if you type in https://questionablecontent.net to the URL bar.  But if you open, say, https://questionablecontent.net/view.php?comic=4150, the sidebar is missing. 

I suspect the issue is the absence of the line starting with `<div class="small-2 medium-expand column"`, which appears to be where you inject the sidebar. It is present on the front page, but not on any of the individual comic pages.

**Comment by trlkly** [comment]
I've confirmed this is the issue. Executing the following line at the top of the script fixes the issue:

    if (location.search != "") {
      document.querySelector('#container > div > div.small-12.medium-expand.column')
        .insertAdjacentHTML('afterend','<div class="small-2 medium-expand column"></div>')
    }

**Comment by ilyvion** [comment]
Argh, it's so frustrating when Jeph (or his webmaster, if it's not him) goes ahead and does these minor edits for seemingly no reason that breaks shit. I'm already having to do all kinds of ridiculous things because said web person doesn't do things logically (e.g. [this crap](https://github.com/Questionable-Content-Extensions/client/blob/develop/assets/js/modules/dom-modifier.js#L70-L74)).

I appreciate your pull request to fix this ❤️; I will evaluate it as soon as I can.
