### ISSUE TITLE
Extension doesn't seem to be loading angular.custom.js

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#43]
All that is on the site is an Apache test page from Amazon's AMI server. The fact that there is anything at all there suggests that you're still paying for the site, so I don't know what's going on. Maybe a forced upgrade lost your settings? 

I hope the database is still available.

**Comment by ilyvion** [comment]
Right, so... back in May the extension stopped working for a few days. That was because... [well](https://www.postandcourier.com/business/customer-websites-go-down-after-charleston-tech-firm-couldnt-pay-its-bills/article_ac3f933c-938d-11ea-bbd0-1b6d236f5bdc.html). Luckily, they managed to get the customers just enough uptime to get their data saved, so I managed to salvage all the comic data. For some days I was certain it'd be gone forever, so... could be worse.

However, I only really had it in me to bring the data and services for the extension back online, so that most users wouldn't notice much of a difference, but as you've obviously noticed, the site itself isn't back. Don't worry though, I'm using AWS to host this time, which, while it feels morally bankrupt, is at least most likely not going to just... randomly go down on me.

I'll see about getting the site back properly at some point in the near future, but you can rest assured that the data itself is safe.

**Comment by trlkly** [comment]
That sounds like the extension itself is still supposed to be working, then. Unfortunately, that is not the case for me. I had assumed the lack of site was why **I see no sidebar at all.** 

That why I came here--to try and download the extension again, to make sure I had the most recent copy. 

 The extension itself seems to be working: the page stays the same while the images load. You sure the database/service are working?

**Comment by ilyvion** [comment]
[Works for me](https://imgur.com/a/HqSAPyr)

I'm sorry the downloads aren't currently working, although to let you in on a little "secret," the download link was just a forward to whatever was the latest release here: https://github.com/Questionable-Content-Extensions/client/releases where you can still download the scripts.

**Comment by ilyvion** [comment]
Oh, also see if going directly to the service works for you, e.g. loading the data for the latest comic: https://questionablecontent.herokuapp.com/api/comicdata/4322

**Comment by trlkly** [comment]
Data is fine.  I did a little more looking, and it seems the problem is that the following URL is not found:

https://questionablextensions.net/scripts/angular.custom.js

Without that, I'm just getting an error in the console about things not being defined. 

It's likely that this file is still cached on your computer. It's not on mine, as I recently upgraded.

**Comment by ilyvion** [comment]
Sorry about that. I've put that up there now. I think the reason I never noticed it is because it's downloaded the first time you install the user script and only loaded from disk after that.

**Comment by trlkly** [comment]
Yep. That's fixed it. Took two loads, but it downloaded it like it was supposed to. 

BTW, an idea came to me overnight: why not set up the main site to redirect to the Github page? That way, if people do click a link to the site, they'll still get to the extension. It'd be a lot less effort than reproducing the site--you'd need one line.

**Comment by ilyvion** [comment]
> BTW, an idea came to me overnight: why not set up the main site to redirect to the Github page? That way, if people do click a link to the site, they'll still get to the extension. It'd be a lot less effort than reproducing the site--you'd need one line.

That's a thought. I had originally planned to have things on the site, such as statistics and other cool things that can be derived from all the data I've collected, but as is probably obvious, I don't really have the surplus energy required to do such things for the time being.
