### ISSUE TITLE
Text color is difficult to read on edit log

### ISSUE THREAD

**Issue by phuzion** [Questionable-Content-Extensions/client#59]
I'm fairly certain that this is an issue on my end, but on the off chance that it is not, I wanted to report a quick bug that I've been seeing for some time.

The text color on the edit log appears to be very **very** difficult to read. I've reinstalled the script and wiped the storage in Tampermonkey.

![image](https://user-images.githubusercontent.com/398094/218622627-490de690-61af-406c-acb4-3cf9d9260d5c.png)

**Comment by ilyvion** [comment]
Yeah, I know. Haven't prioritized it when I've had the mood or will to work on the extension because it's not user facing and honestly exists more as a way for me to track things so I 1) know who to blame if things suddenly go south and 2) have a log that I can "run in reverse" to undo any damage done by a rogue editor.

As for fixing it, I probably won't for this version of the extension. I'm working on a rewrite that'll change/fix a lot of things, and so I'd rather spend my efforts there than fixing the old one.

**Comment by ilyvion** [comment]
I believe this issue has been resolved with the development of the new version of the script and with the release of version 1.0. As such, I'm going to close this issue. Feel free to re-open if you disagree after seeing the new version.
